In [1]:
from layers import LinearLayer, EmbedPosition, Attention, Softmax, CrossEntropy, FeedForward
from data_generators import get_train_test_addition
from utils import onehot

In [2]:
n_digits = 2
n_max = 3* n_digits
m = 10
d = 15
k = 5
p = 20
data = get_train_test_addition(n_digits, samples_per_batch=1, n_batches_train=2)

In [3]:
x = data['x_train'][0]
X = onehot(x, m)

In [4]:
embed = EmbedPosition(n_max, m, d)
att1 = Attention(d,k)
ff1 = FeedForward(d,p)
un_embed = LinearLayer(d,m)
softmax = Softmax()
loss = CrossEntropy()

In [5]:
z_0 = embed.forward(X)
z_1 = att1.forward(z_0)
z_2 = ff1.forward(z_1)
z = un_embed.forward(z_2)
Z = softmax.forward(z)

(1, 6, 6)


In [6]:
loss.forward(Z,y)

NameError: name 'y' is not defined

In [ ]:
Z

NameError: name 'Z' is not defined

In [ ]:
x

array([[3, 8, 5, 6, 4, 9]])

In [ ]:
X

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1.]]])

In [11]:
import numpy as np

a = np.array([[[1, 3, 6, 2, 3, 4],
            [6, 3, 1, 0, 7, 3],
            [4, 7, 3, 7, 1, 3],
            [1, 2, 5, 2, 5, 4],
            [4, 2, 1, 7, 0, 4],
            [6, 5, 0, 5, 4, 6]],
            [[1, 3, 6, 2, 3, 4],
            [6, 3, 1, 0, 7, 3],
            [4, 7, 3, 7, 1, 3],
            [1, 2, 5, 2, 5, 4],
            [4, 2, 1, 7, 0, 4],
            [6, 5, 0, 5, 4, 6]]])

a[:,:, 3] =0
print(a)

[[[1 3 6 0 3 4]
  [6 3 1 0 7 3]
  [4 7 3 0 1 3]
  [1 2 5 0 5 4]
  [4 2 1 0 0 4]
  [6 5 0 0 4 6]]

 [[1 3 6 0 3 4]
  [6 3 1 0 7 3]
  [4 7 3 0 1 3]
  [1 2 5 0 5 4]
  [4 2 1 0 0 4]
  [6 5 0 0 4 6]]]
