# Test om koden er riktig implementert

Her er et forslag til testfunksjoner for å sjekke om koden er riktig implementert.
```assert variabel``` vil gi en feilmelding med mindre variabelen ```variabel = True```. For eksempel vil ```assert a == b``` gi en feilmelding med mindre ```a``` og ```b``` er like.

In [1]:
#For eksempel:
variable = True
assert variable, "You need to change 'variable' to True"

In [2]:
from layers import *
from neural_network import NeuralNetwork
from utils import onehot
import numpy as np

In [3]:
#We choose some arbitrary values for the dimensions
b = 6
n_max = 7
m = 8
n = 5

d = 10
k = 5
p = 20

#Create an arbitrary dataset
x = np.random.randint(0, m, (b,n))
y = np.random.randint(0, m, (b,n_max))

print(x)
print(y)

#initialize the layers
feed_forward = FeedForward(d,p)
attention = Attention(d,k) # Changed from k to n to n_max
embed_pos = EmbedPosition(n_max,m,d)
un_embed = LinearLayer(d,m)
softmax = Softmax()


#a manual forward pass
X = onehot(x, m)
z0 = embed_pos.forward(X)
z1 = feed_forward.forward(z0)
z2 = attention.forward(z1)
z3 = un_embed.forward(z2)
Z = softmax.forward(z3) 

z = np.argmax(Z,axis=1)
print(f"big z: {Z[0]}")
print(f"z: {z[0]}")

#check the shapes
assert X.shape == (b,m,n), f"X.shape={X.shape}, expected {(b,m,n)}"
assert z0.shape == (b,d,n), f"z0.shape={z0.shape}, expected {(b,d,n)}"
assert z1.shape == (b,d,n), f"z1.shape={z1.shape}, expected {(b,d,n)}"
assert z2.shape == (b,d,n), f"z2.shape={z2.shape}, expected {(b,d,n)}"
assert z3.shape == (b,m,n), f"z3.shape={z3.shape}, expected {(b,m,n)}"
assert Z.shape == (b,m,n), f"Z.shape={Z.shape}, expected {(b,m,n)}"

#is X one-hot?
assert X.sum() == b*n, f"X.sum()={X.sum()}, expected {b*n}"


assert np.allclose(Z.sum(axis=1), 1), f"Z.sum(axis=1)={Z.sum(axis=1)}, expected {np.ones(b)}"
assert np.abs(Z.sum() - b*n) < 1e-5, f"Z.sum()={Z.sum()}, expected {b*n}"
assert np.all(Z>=0), f"Z={Z}, expected all entries to be non-negative"


[[7 4 1 6 1]
 [4 2 3 4 3]
 [4 1 0 7 6]
 [2 7 7 0 5]
 [0 5 6 0 3]
 [1 6 2 0 6]]
[[7 3 7 2 5 2 0]
 [0 1 7 6 5 3 4]
 [5 0 6 7 2 6 7]
 [6 4 6 5 7 3 4]
 [5 0 1 5 6 3 5]
 [5 3 5 5 7 4 2]]
w_Q
w_K
w_O
w_V
big z: [[0.12222361 0.12406192 0.12867921 0.12688988 0.12840964]
 [0.13067459 0.13165395 0.13282255 0.12917656 0.1376052 ]
 [0.1242571  0.12507263 0.12911077 0.12454702 0.12610026]
 [0.12395439 0.12361831 0.11664637 0.12251878 0.11655884]
 [0.12078315 0.12688883 0.12149177 0.12185387 0.12734582]
 [0.1242616  0.12398902 0.11155148 0.12814035 0.12049187]
 [0.13171164 0.11790791 0.13336429 0.12629887 0.12025524]
 [0.12213391 0.12680743 0.12633355 0.12057467 0.12323313]]
z: [6 1 6 1 1]


In [4]:

#test the forward pass
x = np.random.randint(0, m, (b,n_max))
X = onehot(x, m)

#we test with a y that is shorter than the maximum length
#COMMENT 2P&1P: WTF!? Skal ikke disse alltid være like lange???????
n_y = n_max - 1
y = np.random.randint(0, m, (b,n_y))
print(y)

#initialize a neural network based on the layers above
network = NeuralNetwork([embed_pos, feed_forward, attention, un_embed, softmax])
#and a loss function
loss = CrossEntropy()

#do a forward pass
Z = network.forward(X)

#compute the loss
L = loss.forward(Z, y)

#get the derivative of the loss wrt Z
grad_Z = loss.backward()

#and perform a backward pass
_ = network.backward(grad_Z)

#and and do a gradient descent step
_ = network.step_gd(0.01)

[[1 6 7 1 6 7]
 [2 1 5 3 4 7]
 [5 4 2 4 3 5]
 [3 4 2 3 7 1]
 [4 1 7 7 2 5]
 [5 1 2 1 0 4]]
w_Q
w_K
w_O
w_V


In [5]:
"""
Here you may add additional tests to for example:

- Check if the ['d'] keys in the parameter dictionaries are not None, or receive something when running backward pass
- Check if the parameters change when you perform a gradient descent step
- Check if the loss decreases when you perform a gradient descent step

This is voluntary, but could be useful.
"""

"\nHere you may add additional tests to for example:\n\n- Check if the ['d'] keys in the parameter dictionaries are not None, or receive something when running backward pass\n- Check if the parameters change when you perform a gradient descent step\n- Check if the loss decreases when you perform a gradient descent step\n\nThis is voluntary, but could be useful.\n"

In [6]:
#check if loss is non-negative
assert L >= 0, f"L={L}, expected L>=0"
assert grad_Z.shape == Z.shape, f"grad_Z.shape={grad_Z.shape}, expected {Z.shape}"

#check if onehot(y) gives zero loss
Y = onehot(y, m)
L = loss.forward(Y, y)
assert L < 1e-5, f"L={L}, expected L<1e-5"


In [7]:
m = np.array([[[.29,.15,.10],
     [.21,.5,.04],
     [.15,.03,.11],
     [.13,.21,.43],
     [.22,.11,.32]],
     [
     [1,0,0],
     [0,1,0],
     [0,0,0],
     [0,0,0],
     [0,0,1]]])



loss = CrossEntropy()

loss.forward(m,np.array([[0,1,4],[0,1,4]]))
loss.backward()

array([[[-1.14942525, -0.        , -0.        ],
        [-0.        , -0.66666665, -0.        ],
        [-0.        , -0.        , -0.        ],
        [-0.        , -0.        , -0.        ],
        [-0.        , -0.        , -1.04166663]],

       [[-0.33333333, -0.        , -0.        ],
        [-0.        , -0.33333333, -0.        ],
        [-0.        , -0.        , -0.        ],
        [-0.        , -0.        , -0.        ],
        [-0.        , -0.        , -0.33333333]]])

In [8]:
x_T = np.array([[[0,0,1],
      [0,0,0]]
     ,[[0,0,0],
       [1,0,0]]])

a = np.ones((3,2))
b = a.T

s = np.einsum('bad,ds,sq,bqk -> bak',x_T,a, b, np.transpose(x_T, axes=(0,2,1)), optimize=True)
for i in range(len(x_T)):
    print(s == (x_T[i]@a)@(b@x_T[i].T))

print(s)


[[[ True  True]
  [ True  True]]

 [[False  True]
  [ True False]]]
[[[False  True]
  [ True False]]

 [[ True  True]
  [ True  True]]]
[[[2. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 2.]]]
